[package]
name = "decoding"
version = "0.1.0"
edition = "2021"

[lib]
name = "glaciers"
crate-type = ["cdylib"]

[dependencies]
alloy = { version = "0.2.0", features = ["json-abi", "dyn-abi"] }
serde_json = "1.0.128"
serde = { version = "1.0.215", features = ["derive"] }
polars = { version = "0.36.2", features = ["lazy", "parquet", "dtype-struct", "strings", "semi_anti_join"]}
thiserror = "1.0.50"
chrono = "0.4.38"
sysinfo = "0.33.0"
tokio = { version = "1.42.0", features = ["full"] }
pyo3 = { version = "0.20.0", features = ["extension-module"] }
pyo3-polars = "0.10.0"
